# Generated by Django 2.0.3 on 2018-03-26 13:06

import count.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mpic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(verbose_name='介绍')),
                ('pub_date', models.DateField(verbose_name='发布时间')),
                ('pic_small', models.FileField(upload_to='bing', verbose_name='缩略图路径')),
                ('pic_full', models.FileField(upload_to='bing', verbose_name='大图路径')),
            ],
            options={
                'verbose_name': 'Bing每日美图',
                'verbose_name_plural': 'Bing每日美图',
                'ordering': ['-pub_date'],
            },
            bases=(models.Model, count.models.ReadNumExpandMethod),
        ),
    ]
